grip_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - slide_right
    - slide_left
    